sda:
  #build: ./docker/
  image: smartdataanalytics/site:develop
  restart: unless-stopped
  container_name: sda
  hostname: sda.tech
  environment:
    - REPO=https://github.com/SmartDataAnalytics/sda.tech
    - BRANCH=master
  ports:
    - 8080:80
  volumes:
    - /var/www/sda.tech/:/data/jekyll/
watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
 #     - /root/.docker/config.json:/config.json
    command: watchtower smartdataanalytics/site:develop --interval 30