sda:
  #build: ./docker/
  image: smartdataanalytics/site:develop
  container_name: sda
  hostname: sda.tech
  environment:
    - REPO=https://github.com/SmartDataAnalytics/sda.tech
    - BRANCH=master
  ports:
    - 8080:80
  volumes:
    - /var/www/sda.tech/:/data/jekyll/