# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: http://example.org/ # the base hostname & protocol for your site, e.g. http://example.com
title: Smart Data Analytics
titleWithAcronym: Smart Data Analytics
author: Institut für Informatik III
email: jens.lehmann@cs.uni-bonn.de
copyrights: Smart Data Analytics, © 2017
addressLineOne: Römerstraße 164
addressLineTwo: 53117 Bonn, Germany
phone: +49 228 73-4315
fax: +49 228 73-4382
description: The Smart Data Analytics (SDA) research group, led by Prof. Dr. Jens Lehmann, has members from the Institute for Computer Science at the University of Bonn, the Fraunhofer Institute for Intelligent Analysis and Information Systems (IAIS) and the Institute for Applied Computer Science Leipzig. At its core, the group investigates machine learning techniques ("analytics") using structured knowledge ("smart data"). The group aims at covering the full spectrum of research including theoretical foundations, algorithms, prototypes and industrial applications.

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: SDA_Research
github_username: SDA
facebook_username: SDAResearch
linkedIn_username: SDA
googlePlus_username: SDA
youtube_username: SDA

#activeVars
activePeople: Professors
activeGroup: Distributed Semantic Analytics
leader: OLIVER OCTOPUS

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-rdf
  - jekyll-twitter-plugin

#Configuration of jekyll-rdf in our template
jekyll_rdf:
    path: "rdf-data/simpsons.ttl"
    language: "en"
    include_blank: true
    render_orphaned_uris: true
    restriction: "SELECT ?resourceUri WHERE {
                 { ?resourceUri a <http://example.org/group> . }
                UNION { ?resourceUri a <http://example.org/project> . }
                UNION { ?resourceUri a <http://example.org/publication> . }
                UNION { ?resourceUri a <http://example.org/job> . }
                UNION { ?resourceUri a <http://example.org/teaching> . }
                UNION { ?resourceUri a <http://example.org/partners> . }
                UNION { ?resourceUri a <http://xmlns.com/foaf/0.1/Person> . }
                UNION { ?resourceUri a <http://xmlns.com/foaf/0.1/Document> . }
                }"
    default_template: "default.html"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Person" : "person.html"
        "http://example.org/group" : "group.html"
        "http://example.org/project" : "project.html"
        "http://example.org/job" : "job.html"
        "http://example.org/teaching" : "teaching.html"
        "http://example.org/publication" : "publication.html"
        "http://xmlns.com/foaf/0.1/Document" : "document.html"
    instance_template_mappings:
        "http://example.org/" : "home.html"
        "http://example.org/group" : "groupmain.html"
        "http://example.org/publication" : "publicationmain.html"
        "http://example.org/job" : "jobmain.html"
        "http://example.org/teaching" : "teachingmain.html"
        "http://example.org/project" : "projectmain.html"
        "http://example.org/partners" : "partners.html"
        "http://example.org/about" : "page.html"
        "http://example.org/people" : "people.html"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
